;;; Compiled snippets and support files for `org-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'org-mode
		     '(("<web" "#+include: \"../asserts/header.org\"\n#+title: ${1:`\n(string-join\n (mapcar #'capitalize\n         (split-string\n          (let (case-fold-search)\n            (replace-regexp-in-string\n             \"\\\\([[:lower:]]\\\\)\\\\([[:upper:]]\\\\)\" \"\\\\1 \\\\2\"\n             (replace-regexp-in-string \"\\\\([[:upper:]]\\\\)\\\\([[:upper:]][0-9[:lower:]]\\\\)\"\n                                       \"\\\\1 \\\\2\" (file-name-base(file-name-base buffer-file-name)))))\n          \"[^[:word:]0-9]+\"\n          )) \" \" )\n`}\n#+description: ${2:description}\n#+author: Aditya Yadav\n#+setupfile: ../theme-readtheorg-local.setup\n\n$0\n\n#+INCLUDE: \"../asserts/footer.org\"" "Org-website-template" t nil nil "/home/aditya-yadav/.config/emacs/snippets/org-mode/__Website" nil nil)
		       ("<class" "#+title: ${1:`\n(string-join\n (mapcar #'capitalize\n         (split-string\n          (let (case-fold-search)\n            (replace-regexp-in-string\n             \"\\\\([[:lower:]]\\\\)\\\\([[:upper:]]\\\\)\" \"\\\\1 \\\\2\"\n             (replace-regexp-in-string \"\\\\([[:upper:]]\\\\)\\\\([[:upper:]][0-9[:lower:]]\\\\)\"\n                                       \"\\\\1 \\\\2\" (file-name-base(file-name-base buffer-file-name)))))\n          \"[^[:word:]0-9]+\"\n          )) \" \" )\n`}\n#+description: ${2:description}\n#+latex_header_extra: \\hypersetup{colorlinks=true,linkcolor=blue}\n#+author: Aditya Yadav\n\n* ${4:heading}\n$0\n" "org-default" t nil nil "/home/aditya-yadav/.config/emacs/snippets/org-mode/__Class" nil nil)
		       ("<blog" "#+title: ${1:`\n(string-join\n (mapcar #'capitalize\n         (split-string\n          (let (case-fold-search)\n            (replace-regexp-in-string\n             \"\\\\([[:lower:]]\\\\)\\\\([[:upper:]]\\\\)\" \"\\\\1 \\\\2\"\n             (replace-regexp-in-string \"\\\\([[:upper:]]\\\\)\\\\([[:upper:]][0-9[:lower:]]\\\\)\"\n                                       \"\\\\1 \\\\2\" (file-name-base(file-name-base buffer-file-name)))))\n          \"[^[:word:]0-9]+\"\n          )) \" \" )\n`}\n#+description: ${2:description}\n#+export_file_name: ~/Personal/Git-repos/Linux-Blog/${3:`(file-name-sans-extension (file-name-sans-extension (string-join (last (split-string buffer-file-name \"/\") 2) \"/\")))`}\n#+author: Aditya Yadav\n\n$0" "Blog Setup Template" t nil nil "/home/aditya-yadav/.config/emacs/snippets/org-mode/__Blog" nil nil)))


;;; Do not edit! File generated at Sat Jan 28 16:42:52 2023
