;;; Compiled snippets and support files for `c++-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'c++-mode
		     '(("<cp" "#include <bits/stdc++.h>\nusing namespace std;\n\n#define clz __builtin_clz\n#define ctz __builtin_ctz\n#define cnz __builtin_popcount\n#define clmsb __builtin_clrsb\n#define bitswap __builtin_bswap32\n\n#define clzl __builtin_clzl\n#define ctzl __builtin_ctzl\n#define cnzl __builtin_popcountl\n#define clmsbl __builtin_clrsb\n#define bitswapl __builtin_bswap64\n\n#define mod       1000000007\n#define mods      998244353\n#define all(x)    (x).begin(), (x).end()\n#define pwp(x,y)  fixed<<setprecision(y)<<x\n#define FIO()     ios_base::sync_with_stdio(0); cin.tie(0); cout.tie(0)\n#define repeat    int t;cin>>t;while(t--)\n\nvector<int>sieve(int n){int*arr=new int[n+1];vector<int>vect;for(int i=2;i<=n;i++)if(arr[i]==0){vect.push_back(i);for(int j=2*i;j<=n;j+=i)arr[j]=1;}free(arr);return vect;}\nint power(int x,unsigned int y,int m){int res=1;x=x%m;if(x==0)return 0;while(y>0){if(y&1)res=(res*x)%m;y=y>>1;x=(x*x)%m;}return res;}\nint mod_inverse(int a,int p){return power(a,p-2,p);}\nint mod_add(int a,int b,int m){a=a%m;b=b%m;return(((a+b)%m)+m)%m;}\nint mod_mul(int a,int b,int m){a=a%m;b=b%m;return(((a*b)%m)+m)%m;}\nint mod_sub(int a,int b,int m){a=a%m;b=b%m;return(((a-b)%m)+m)%m;}\nint mod_div(int a,int b,int m){a=a%m;b=b%m;return(mod_mul(a,mod_inverse(b,m),m)+m)%m;}\n\n\n#if !defined(ONLINE_JUDGE) && 1\n#define dbg(x) cerr << #x <<\" \"; _print(x); cerr << endl;\n#else\n#define dbg(x)\n#endif\n\ntemplate <class T> void _print(T t) {cerr << t;}\nvoid _print(string t) {cerr << '\"' << t << '\"';}\ntemplate <class T, class V> void _print(pair <T, V> p) {cerr << \"{\"; _print(p.first); cerr << \",\"; _print(p.second); cerr << \"}\";}\ntemplate <class T> void _print(vector <T> v) {cerr << \"[ \"; for (T i : v) {_print(i); cerr << \" \";} cerr << \"]\"<<endl;}\ntemplate <class T> void _print(set <T> v) {cerr << \"[ \"; for (T i : v) {_print(i); cerr << \" \";} cerr << \"]\";}\ntemplate <class T> void _print(multiset <T> v) {cerr << \"[ \"; for (T i : v) {_print(i); cerr << \" \";} cerr << \"]\";}\ntemplate <class T, class V> void _print(map <T, V> v) {cerr << \"[ \"; for (auto i : v) {_print(i); cerr << \" \";} cerr << \"]\";}\n\n\nint main() {\n    int testcase;\n    cin >> testcase;\n    while(testcase--){\n        $0\n    }\n    return 0;\n}" "competitive-programming" t nil nil "/home/aditya-yadav/.config/emacs/snippets/c++-mode/__CP" nil "")
		       ("__CHEF" "#include <bits/stdc++.h>\n\nusing namespace std;\n\nint main(int argc, char *argv[]) {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int testcase;\n    cin >> testcase;\n    while(testcase--){\n        $0\n    }\n    return 0;\n}\n" "Basic testcase while loop" t nil nil "/home/aditya-yadav/.config/emacs/snippets/c++-mode/__CHEF" nil "")))


;;; Do not edit! File generated at Sat Jan 28 16:42:52 2023
